#include <iostream>
#include <cmath>
using namespace std;

int main()
{
    int x1, y1, x2, y2;

    cout << "Enter starting point (x1, y1): ";
    cin >> x1 >> y1;

    cout << "Enter ending point (x2, y2): ";
    cin >> x2 >> y2;

    int dx = x2 - x1;
    int dy = y2 - y1;

    int steps = max(abs(dx), abs(dy));

    float xIncrement = (float)dx / steps;
    float yIncrement = (float)dy / steps;

    float x = x1;
    float y = y1;

    cout << "\nPoints generated by DDA:\n";

    for (int i = 0; i <= steps; i++)
    {
        cout << "(" << round(x) << ", " << round(y) << ")" << endl;

        x = x + xIncrement;
        y = y + yIncrement;
    }

    return 0;
}
